### ISSUE TITLE
When global is set to "true" along with host affinity for a srevice , all containers are getting launched on the same host.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1012]
Server version - Master build from 06/01

Steps to reproduce the problem:
Have multiple hosts (3 in my case) which has tag set to "foo1=bar1".
Create a service with global set to "true" and host affinity set to "foo1=bar"1.
Activate service.

Service scales to 3 as expected. But all the containers get launched in the 1 of the hosts that had label - "foo1=bar1".

Following are the labels that were set on the service: 
"labels": {
"io.rancher.scheduler.global": "true",
"io.rancher.scheduler.affinity:host_label": "foo1=bar1",
},

Expected Behavior:
1 Container should get launched in each of the hosts that has label "foo1=bar1".

**Comment by sangeethah** [comment]
Also when I create a service with no labels ( global is not set and no affinity host labels) and activate the service I see all the containers of the service always go to the same host.
I tried at least 5 times and see that containers of the same service land in the same host.

**Comment by sonchang** [comment]
Should be fixed now.  This was merged into master late yesterday.

**Comment by sangeethah** [comment]
Tested with server version -  rancher/server:v0.23.0-rc2  

This issue is still reproducible.
When global is set to "true" along with host affinity for a service , all containers are getting launched on the same host.

**Comment by sonchang** [comment]
Just merged in

**Comment by sangeethah** [comment]
Tested with server version - rancher/server:v0.23.0-rc5
Create a service with global set to "true" and host affinity set to "foo1=bar"  when there are 3 hosts set with labels "foo1=bar1.
Activated service.
1 container gets deployed in each of the hosts.
