### ISSUE TITLE
[UI][Private Registry]  Edit Private Registry page does not show address field.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#265]
Version -V0.12.0

Edit Private Registry page does not show address field.

If we allow for editing the address field , make it an editable field. Else show the contents of this field.

![screen shot 2015-03-19 at 8 49 02 am](https://cloud.githubusercontent.com/assets/4266958/6734393/2eeda966-ce15-11e4-9365-c97c730a32a9.png)

**Comment by vincent99** [comment]
Fixed in rancherio/ui#104

**Comment by tfiduccia** [comment]
Verified Fixed although you still cannot edit the address field.  It is displayed on edit page.
